/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SOMAVET_H_RPCGEN
#define _SOMAVET_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int vet_len;
	int *vet_val;
} vet;

#define PROG 200
#define VERSION 100

#if defined(__STDC__) || defined(__cplusplus)
#define SOMA 1
extern  int * soma_100(vet *, CLIENT *);
extern  int * soma_100_svc(vet *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SOMA 1
extern  int * soma_100();
extern  int * soma_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vet (XDR *, vet*);

#else /* K&R C */
extern bool_t xdr_vet ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SOMAVET_H_RPCGEN */
