/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "somaVet.h"


int funcao(char *host, CLIENT *clnt, vet *vetor)
{
	int *result;
	result = soma_100(vetor,clnt);

	if(result == NULL)
	{
		printf("Deu erro no servidor ou na comunicacao\n");
		return -1;
	}

	return (*result);
}


int
main (int argc, char *argv[])
{
	char *host = argv[1];
	CLIENT *clnt;
	
	vet *vetor = malloc(sizeof(vet));
	vetor -> vet_val = malloc(sizeof(int) * (argc - 2));
	vetor -> vet_len = argc - 2;
	
	for(int i = 2; i < argc; i++)
	{
		vetor -> vet_val[i - 2] = atoi(argv[i]);
	}
	
	clnt = clnt_create(host, PROG, VERSION,"udp");
	
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	int result = funcao(host, clnt, vetor);
	printf("Soma: %d\n", result);
	exit (0);
}
