/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "somaVet.h"

int *
soma_100_svc(vet *argp, struct svc_req *rqstp)
{
	static int result;
	result = 0;
	
	int size = argp -> vet_len;
	
	for (int i = 0; i < size; i++)
	{
		result += argp -> vet_val[i];
	}

	return &result;
}
