/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "somaVet.h"

bool_t
xdr_vet (XDR *xdrs, vet *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vet_val, (u_int *) &objp->vet_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
