/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "soma.h"

void soma_lista_55(char *host, CLIENT *clnt, lista *cabeca)
{
	int *resultado;

	resultado = add_55(cabeca,clnt);
	if(resultado == NULL)
	{
		printf("Deu erro no servidor\n");
	}
	printf("Soma: %d\n",*resultado);

}

int main(int argc, char *argv[])
{
	char *host = argv[1];
	CLIENT *clnt;
	
	if (argc < 2)
	{
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	
	clnt = clnt_create(host, SOMA_LISTA, SOMA_LISTA_VERSION, "udp");

	lista *cabeca = malloc(sizeof(lista));
	cabeca -> num = 0;
	cabeca -> prox = NULL;

	for(int i = 2; i < argc; i++)
	{
		lista *novo = malloc(sizeof(lista));
		novo -> num = atoi(argv[i]);
		novo -> prox = cabeca -> prox;
		cabeca -> prox = novo;
	}
	cabeca = cabeca -> prox;

	host = argv[1];
	soma_lista_55(host,clnt,cabeca);
	exit(0);
}