/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SOMA_H_RPCGEN
#define _SOMA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif



struct lista {
	int num;
	struct lista *prox;
};
typedef struct lista lista;

#define SOMA_LISTA 0x13
#define SOMA_LISTA_VERSION 55

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  int * add_55(lista *, CLIENT *);
extern  int * add_55_svc(lista *, struct svc_req *);
extern int soma_lista_55_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  int * add_55();
extern  int * add_55_svc();
extern int soma_lista_55_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_lista (XDR *, lista*);

#else /* K&R C */
extern bool_t xdr_lista ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SOMA_H_RPCGEN */
