/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "soma.h"

int *add_55_svc(lista *argp, struct svc_req *rqstp)
{
	static int result;
	result = 0;

	while (argp != NULL)
	{
		result += argp->num;
		argp = argp->prox;
	}

	return &result;
}