/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "soma_lista.h"

int *
soma_1_svc(lista *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	while (argp)
	{
		result += argp->num;
		argp = argp->prox;
	}
	

	return &result;
}
