/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SOMA_LISTA_H_RPCGEN
#define _SOMA_LISTA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct lista {
	int num;
	struct lista *prox;
};
typedef struct lista lista;


#define PROG 0x13
#define VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define soma 1
extern  int * soma_1(lista *, CLIENT *);
extern  int * soma_1_svc(lista *, struct svc_req *);
extern int prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define soma 1
extern  int * soma_1();
extern  int * soma_1_svc();
extern int prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_lista (XDR *, lista*);
extern  bool_t xdr_lista (XDR *, lista*);

#else /* K&R C */
extern bool_t xdr_lista ();
extern bool_t xdr_lista ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SOMA_LISTA_H_RPCGEN */
